### ISSUE TITLE
demojize() got an unexpected keyword argument 'language'

### ISSUE THREAD

**Issue by eg384** [finiteautomata/pysentimiento#4]
I am having an issue when running analyzer.predict(). I am using the sample code from Colab's notebook:

```
from pysentimiento import SentimentAnalyzer
analyzer = SentimentAnalyzer(lang="es")
analyzer.predict("Qué gran jugador es Messi")
```

But I am receiving this error message:
```

C:\Users\X\VS Code Repositories\X>C:/Users/X/AppData/Local/Programs/Python/Python37/python.exe "c:/Users/X/VS Code Repositories/X/test.py"
Traceback (most recent call last):
  File "c:/Users/C/VS Code Repositories/X/test.py", line 22, in <module>
    analyzer.predict("Qué gran jugador es Messi")
  File "C:\Users\C\AppData\Local\Programs\Python\Python37\Lib\site-packages\pysentimiento\analyzer.py", line 74, in predict
    sentence = preprocess_tweet(sentence, **self.preprocessing_args)
  File "C:\Users\C\AppData\Local\Programs\Python\Python37\Lib\site-packages\pysentimiento\preprocessing.py", line 160, in preprocess_tweet
    text = emoji.demojize(text, language=lang, delimiters=("|", "|"))
TypeError: demojize() got an unexpected keyword argument 'language'
```

I have pysentimento version 0.2.0. The weird thing is that I tried that same code on Colab's example and it runs successfully. What may be the reason for this issue?

**Comment by eg384** [comment]
Fixed! I just need to upgrade the emoji package

**Comment by finiteautomata** [comment]
Thanks! I will check if it is correctly set in `setup.py`
